CREATE TABLE "public"."customer_tbl1"(c_customer_sk          integer NOT NULL encode az64,
                                      c_customer_id          character(16) NOT NULL encode lzo,
                                      c_current_cdemo_sk     integer encode az64,
                                      c_current_hdemo_sk     integer encode az64,
                                      c_current_addr_sk      integer encode az64,
                                      c_first_shipto_date_sk integer encode az64,
                                      c_first_sales_date_sk  integer encode az64,
                                      c_salutation           character(10) encode lzo,
                                      c_first_name           character(20) encode lzo,
                                      c_last_name            character(30) encode lzo,
                                      c_preferred_cust_flag  character(1) encode lzo,
                                      c_birth_day            integer encode az64,
                                      c_birth_month          integer encode az64,
                                      c_birth_year           integer encode az64,
                                      c_birth_country        character varying(20) encode lzo,
                                      c_login                character(13) encode lzo,
                                      c_email_address        character(50) encode lzo,
                                      c_last_review_date_sk  integer encode az64)distkey(c_customer_sk);

CREATE TABLE "public"."customer_tbl2"(c_customer_sk          integer NOT NULL encode az64,
                                      c_customer_id          character(16) NOT NULL encode lzo,
                                      c_current_cdemo_sk     integer encode az64,
                                      c_current_hdemo_sk     integer encode az64,
                                      c_current_addr_sk      integer encode az64,
                                      c_first_shipto_date_sk integer encode az64,
                                      c_first_sales_date_sk  integer encode az64,
                                      c_salutation           character(10) encode lzo,
                                      c_first_name           character(20) encode lzo,
                                      c_last_name            character(30) encode lzo,
                                      c_preferred_cust_flag  character(1) encode lzo,
                                      c_birth_day            integer encode az64,
                                      c_birth_month          integer encode az64,
                                      c_birth_year           integer encode az64,
                                      c_birth_country        character varying(20) encode lzo,
                                      c_login                character(13) encode lzo,
                                      c_email_address        character(50) encode lzo,
                                      c_last_review_date_sk  integer encode az64)distkey(c_customer_sk);
CREATE TABLE "public"."customer_tbl3"(c_customer_sk          integer NOT NULL encode az64,
                                      c_customer_id          character(16) NOT NULL encode lzo,
                                      c_current_cdemo_sk     integer encode az64,
                                      c_current_hdemo_sk     integer encode az64,
                                      c_current_addr_sk      integer encode az64,
                                      c_first_shipto_date_sk integer encode az64,
                                      c_first_sales_date_sk  integer encode az64,
                                      c_salutation           character(10) encode lzo,
                                      c_first_name           character(20) encode lzo,
                                      c_last_name            character(30) encode lzo,
                                      c_preferred_cust_flag  character(1) encode lzo,
                                      c_birth_day            integer encode az64,
                                      c_birth_month          integer encode az64,
                                      c_birth_year           integer encode az64,
                                      c_birth_country        character varying(20) encode lzo,
                                      c_login                character(13) encode lzo,
                                      c_email_address        character(50) encode lzo,
                                      c_last_review_date_sk  integer encode az64)distkey(c_customer_sk);
CREATE TABLE "public"."customer_tbl4"(c_customer_sk          integer NOT NULL encode az64,
                                      c_customer_id          character(16) NOT NULL encode lzo,
                                      c_current_cdemo_sk     integer encode az64,
                                      c_current_hdemo_sk     integer encode az64,
                                      c_current_addr_sk      integer encode az64,
                                      c_first_shipto_date_sk integer encode az64,
                                      c_first_sales_date_sk  integer encode az64,
                                      c_salutation           character(10) encode lzo,
                                      c_first_name           character(20) encode lzo,
                                      c_last_name            character(30) encode lzo,
                                      c_preferred_cust_flag  character(1) encode lzo,
                                      c_birth_day            integer encode az64,
                                      c_birth_month          integer encode az64,
                                      c_birth_year           integer encode az64,
                                      c_birth_country        character varying(20) encode lzo,
                                      c_login                character(13) encode lzo,
                                      c_email_address        character(50) encode lzo,
                                      c_last_review_date_sk  integer encode az64)distkey(c_customer_sk);
CREATE TABLE "public"."customer_tbl5"(c_customer_sk          integer NOT NULL encode az64,
                                      c_customer_id          character(16) NOT NULL encode lzo,
                                      c_current_cdemo_sk     integer encode az64,
                                      c_current_hdemo_sk     integer encode az64,
                                      c_current_addr_sk      integer encode az64,
                                      c_first_shipto_date_sk integer encode az64,
                                      c_first_sales_date_sk  integer encode az64,
                                      c_salutation           character(10) encode lzo,
                                      c_first_name           character(20) encode lzo,
                                      c_last_name            character(30) encode lzo,
                                      c_preferred_cust_flag  character(1) encode lzo,
                                      c_birth_day            integer encode az64,
                                      c_birth_month          integer encode az64,
                                      c_birth_year           integer encode az64,
                                      c_birth_country        character varying(20) encode lzo,
                                      c_login                character(13) encode lzo,
                                      c_email_address        character(50) encode lzo,
                                      c_last_review_date_sk  integer encode az64)distkey(c_customer_sk);
CREATE TABLE "public"."customer_tbl6"(c_customer_sk          integer NOT NULL encode az64,
                                      c_customer_id          character(16) NOT NULL encode lzo,
                                      c_current_cdemo_sk     integer encode az64,
                                      c_current_hdemo_sk     integer encode az64,
                                      c_current_addr_sk      integer encode az64,
                                      c_first_shipto_date_sk integer encode az64,
                                      c_first_sales_date_sk  integer encode az64,
                                      c_salutation           character(10) encode lzo,
                                      c_first_name           character(20) encode lzo,
                                      c_last_name            character(30) encode lzo,
                                      c_preferred_cust_flag  character(1) encode lzo,
                                      c_birth_day            integer encode az64,
                                      c_birth_month          integer encode az64,
                                      c_birth_year           integer encode az64,
                                      c_birth_country        character varying(20) encode lzo,
                                      c_login                character(13) encode lzo,
                                      c_email_address        character(50) encode lzo,
                                      c_last_review_date_sk  integer encode az64)distkey(c_customer_sk);

CREATE TABLE "public"."rs_customer_fact"(c_customer_sk          integer NOT NULL encode az64,
                                      c_customer_id          character(16) NOT NULL encode lzo,
                                      c_current_cdemo_sk     integer encode az64,
                                      c_current_hdemo_sk     integer encode az64,
                                      c_current_addr_sk      integer encode az64,
                                      c_first_shipto_date_sk integer encode az64,
                                      c_first_sales_date_sk  integer encode az64,
                                      c_salutation           character(10) encode lzo,
                                      c_first_name           character(20) encode lzo,
                                      c_last_name            character(30) encode lzo,
                                      c_preferred_cust_flag  character(1) encode lzo,
                                      c_birth_day            integer encode az64,
                                      c_birth_month          integer encode az64,
                                      c_birth_year           integer encode az64,
                                      c_birth_country        character varying(20) encode lzo,
                                      c_login                character(13) encode lzo,
                                      c_email_address        character(50) encode lzo,
                                      c_last_review_date_sk  integer encode az64)distkey(c_customer_sk);